name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH & Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}       # ✅ Use public DNS
        username: ${{ secrets.EC2_USER }}   # usually ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}     # PEM key stored as secret
        port: 22
        script: |
          cd /home/ec2-user/your-app-folder
          git pull origin main
          npm install
          fuser -k 3000/tcp || true
          nohup node server.js > app.log 2>&1 &
          echo "✅ App deployed and started!"
