name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Pulling latest code..."
          cd /home/ec2-user/your-app-folder
          git pull origin main

          echo "Installing dependencies..."
          npm install

          echo "Killing existing app (if any)..."
          fuser -k 3000/tcp || true

          echo "Starting app using node..."
          nohup node server.js > app.log 2>&1 &

          echo "App deployed and running!"
